In [1]:
import os
import tensorflow as tf
import numpy as np
import pandas as pd

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
DATASET_PATH = os.path.join("/kaggle/input", "kaggle-llm-science-exam")

**GitHub command to pull data from the "master" branch in multiple_choice_quesiton_answering Github repository to the current working environment(to the "datasets" folder).**

**Reading the training dataset.**

In [3]:
TRAINING_DATASET = os.path.join(DATASET_PATH, "train.csv")
train_df = pd.read_csv(TRAINING_DATASET)
train_df

id                                             prompt  \
0      0  Which of the following statements accurately d...   
1      1  Which of the following is an accurate definiti...   
2      2  Which of the following statements accurately d...   
3      3  What is the significance of regularization in ...   
4      4  Which of the following statements accurately d...   
..   ...                                                ...   
195  195  What is the relation between the three moment ...   
196  196  What is the throttling process, and why is it ...   
197  197  What happens to excess base metal as a solutio...   
198  198  What is the relationship between mass, force, ...   
199  199  What did Arthur Eddington discover about two o...   

                                                     A  \
0    MOND is a theory that reduces the observed mis...   
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol was reconstructed as a fe...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem expresses the relatio...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often solidify, bec...   
198  Mass is a property that determines the weight ...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     B  \
0    MOND is a theory that increases the discrepanc...   
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol is a representation of th...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often crystallize-o...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     C  \
0    MOND is a theory that explains the missing bar...   
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol is a representation of a ...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem describes the relatio...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often dissolve, bec...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     D  \
0    MOND is a theory that reduces the discrepancy ...   
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol represents three interloc...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often liquefy, beco...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     E answer  
0    MOND is a theory that eliminates the observed ...      D  
1    Dynamic scaling refers to the evolution of sel...      A  
2    The triskeles symbol is a representation of th...      A  
3    Regularizing the mass-energy of an electron wi...      C  
4    The angular spacing of features in the diffrac...      D  
..                                                 ...    ...  
195  The thre

**Function to convert the answer of each question into numerical labels, to feed to NLP model later.**

In [4]:
def letter_to_label(letter):
    if 'A' <= letter <= 'Z':
        return ord(letter) - ord('A')
    else:
        return None  # Handle invalid input (not an uppercase letter)
letter_to_label('E')

4

**Making a new column "label" to store numerical label of the answer.**

In [5]:
train_df["label"] = train_df["answer"].map(letter_to_label)
train_df

id                                             prompt  \
0      0  Which of the following statements accurately d...   
1      1  Which of the following is an accurate definiti...   
2      2  Which of the following statements accurately d...   
3      3  What is the significance of regularization in ...   
4      4  Which of the following statements accurately d...   
..   ...                                                ...   
195  195  What is the relation between the three moment ...   
196  196  What is the throttling process, and why is it ...   
197  197  What happens to excess base metal as a solutio...   
198  198  What is the relationship between mass, force, ...   
199  199  What did Arthur Eddington discover about two o...   

                                                     A  \
0    MOND is a theory that reduces the observed mis...   
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol was reconstructed as a fe...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem expresses the relatio...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often solidify, bec...   
198  Mass is a property that determines the weight ...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     B  \
0    MOND is a theory that increases the discrepanc...   
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol is a representation of th...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often crystallize-o...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     C  \
0    MOND is a theory that explains the missing bar...   
1    Dynamic scaling refers to the evolution of sel...   
2    The triskeles symbol is a representation of a ...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem describes the relatio...   
196  The throttling process is a steady adiabatic f...   
197  The excess base metal will often dissolve, bec...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     D  \
0    MOND is a theory that reduces the discrepancy ...   
1    Dynamic scaling refers to the non-evolution of...   
2    The triskeles symbol represents three interloc...   
3    Regularizing the mass-energy of an electron wi...   
4    The angular spacing of features in the diffrac...   
..                                                 ...   
195  The three moment theorem is used to calculate ...   
196  The throttling process is a steady flow of a f...   
197  The excess base metal will often liquefy, beco...   
198  Mass is an inertial property that determines a...   
199  Arthur Eddington showed that two of Einstein's...   

                                                     E answer  label  
0    MOND is a theory that eliminates the observed ...      D      3  
1    Dynamic scaling refers to the evolution of sel...      A      0  
2    The triskeles symbol is a representation of th...      A      0  
3    Regularizing the mass-energy of an electron wi...      C      2  
4    The angular spacing of features in the diffrac...      D      3  
..                                 

**The function Dataset.from_pandas() will convert the Pandas Dataframe to a Dataset type used in the library Transformers. We do this to make it easier to incorporate preprocessing functions which are in the Transformers library to our dataset. Later we will fine-tune a huge, well-known pre-trained NLP model to our dataset to predict the answer of multiple choice question.**

In [6]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
train_dataset

Dataset({
    features: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'label'],
    num_rows: 200
})

In [7]:
train_dataset[0:2]

{'id': [0, 1],
 'prompt': ['Which of the following statements accurately describes the impact of Modified Newtonian Dynamics (MOND) on the observed "missing baryonic mass" discrepancy in galaxy clusters?',
  'Which of the following is an accurate definition of dynamic scaling in self-similar systems?'],
 'A': ['MOND is a theory that reduces the observed missing baryonic mass in galaxy clusters by postulating the existence of a new form of matter called "fuzzy dark matter."',
  'Dynamic scaling refers to the evolution of self-similar systems, where data obtained from snapshots at fixed times exhibits similarity to the respective data taken from snapshots of any earlier or later time. This similarity is tested by a certain time-dependent stochastic variable x.'],
 'B': ['MOND is a theory that increases the discrepancy between the observed missing baryonic mass in galaxy clusters and the measured velocity dispersions from a factor of around 10 to a factor of about 20.',
  'Dynamic scaling

**The AutoTokenizer class in this case will download the pretrained BertModel tokenizer to our working environment.**

In [8]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(os.path.join("/kaggle/input", "roberta-base"))

**This function will concatenate the question with both the five options for each question in the training dataset, and then using the tokenizer loaded above to tokenized the resulting sentence from that concatenation.**

In [9]:
options = ["A", "B", "C", "D", "E"]


def multiple_choice_question_preprocessing_function(example):
    first_sentences = [ example["prompt"] for i in range(5) ]
    second_sentences = [
        example[option] for option in options
    ]

    tokenized_examples = tokenizer(first_sentences, second_sentences, truncation=True)
    return {k: v for k, v in tokenized_examples.items()}

**Mapping the function to the dataset and we will have the tokenized training dataset.**

In [10]:
tokenized_train_dataset = train_dataset.map(multiple_choice_question_preprocessing_function)

  0%|          | 0/200 [00:00<?, ?ex/s]

**We view the keys of the resulting tokenized dataset. Two new keys has been appended to the dataset:"input_ids", which records the tokenized sentence and "attention mask", which records attention mask for usage by the attention layers in the pretrained model.**

In [11]:
tokenized_train_dataset[0].keys()

dict_keys(['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'label', 'input_ids', 'attention_mask'])

**Corresponding Tokenized sentences and attention masks for one question have the same length as you can see here.**

In [12]:
for i, tokenized_sentence in enumerate(tokenized_train_dataset[0]["input_ids"]):
    print(f"The length of sentence number {i} is", len(tokenized_sentence))
print("---------------------------")
for i, tokenized_sentence in enumerate(tokenized_train_dataset[0]["attention_mask"]):
    print(f"The length of sentence number {i} is", len(tokenized_sentence))

The length of sentence number 0 is 73
The length of sentence number 1 is 76
The length of sentence number 2 is 76
The length of sentence number 3 is 76
The length of sentence number 4 is 72
---------------------------
The length of sentence number 0 is 73
The length of sentence number 1 is 76
The length of sentence number 2 is 76
The length of sentence number 3 is 76
The length of sentence number 4 is 72


In [13]:
from dataclasses import dataclass
from transformers.tokenization_utils_base import PreTrainedTokenizerBase, PaddingStrategy
from typing import Optional, Union
import tensorflow as tf


@dataclass
class DataCollatorForMultipleChoice:
    """
    Data collator that will dynamically pad the inputs for multiple choice received.
    """

    tokenizer: PreTrainedTokenizerBase
    padding: Union[bool, str, PaddingStrategy] = True
    max_length: Optional[int] = None
    pad_to_multiple_of: Optional[int] = None

    def __call__(self, features):
        label_name = "label" if "label" in features[0].keys() else "labels"
        labels = [feature.pop(label_name) for feature in features]
        batch_size = len(features)
        num_choices = len(features[0]["input_ids"])
        flattened_features = [
            [{k: v[i] for k, v in feature.items()} for i in range(num_choices)] for feature in features
        ]
        flattened_features = sum(flattened_features, [])

        batch = self.tokenizer.pad(
            flattened_features,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors="tf",
        )

        batch = {k: tf.reshape(v, (batch_size, num_choices, -1)) for k, v in batch.items()}
        batch["labels"] = tf.convert_to_tensor(labels, dtype=tf.int64)
        return batch

In [14]:
from transformers import create_optimizer
from transformers import TFAutoModelForMultipleChoice
from datasets import Dataset
from transformers.keras_callbacks import KerasMetricCallback
import random

In [15]:
import numpy as np

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return accuracy.compute(predictions = predictions, references = labels)

In [16]:
from transformers import create_optimizer

batch_size = 16
num_train_epochs = 10
total_train_steps = (len(tokenized_train_dataset) // batch_size) * num_train_epochs
optimizer, schedule = create_optimizer(init_lr = 1e-5, num_warmup_steps = 0, num_train_steps = total_train_steps)

In [17]:
from transformers import TFAutoModelForMultipleChoice

model = TFAutoModelForMultipleChoice.from_pretrained(os.path.join("/kaggle/input", "roberta-base"))
model.summary()

All model checkpoint layers were used when initializing TFRobertaForMultipleChoice.

All the layers of TFRobertaForMultipleChoice were initialized from the model checkpoint at /kaggle/input/roberta-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForMultipleChoice for predictions without further training.


Model: "tf_roberta_for_multiple_choice"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 roberta (TFRobertaMainLayer  multiple                 124645632 
 )                                                               
                                                                 
 dropout_37 (Dropout)        multiple                  0         
                                                                 
 classifier (Dense)          multiple                  769       
                                                                 
Total params: 124,646,401
Trainable params: 124,646,401
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer = optimizer)  # No loss argument!= optimizer)  # No loss argument!

In [19]:
def cross_validation_training(cv = 5):

    cv_accuracy = []

    index_list = [i for i in range(len(tokenized_train_dataset))]
    random.shuffle(index_list)
    index_lists = np.array_split(index_list, cv)

    for cv_phase in range(cv):
        batch_size = 8
        num_train_epochs = 15
        total_train_steps = (len(tokenized_train_dataset) // batch_size) * num_train_epochs
        optimizer, schedule = create_optimizer(init_lr = 1e-5, num_warmup_steps = 0, num_train_steps = total_train_steps)

        model = TFAutoModelForMultipleChoice.from_pretrained("roberta-base")

        data_collator = DataCollatorForMultipleChoice(tokenizer = tokenizer)
        tf_train_set = model.prepare_tf_dataset(
            Dataset.from_dict(tokenized_train_dataset[ np.setdiff1d(np.array(index_list), index_lists[cv_phase])]),
            shuffle = True,
            batch_size = batch_size,
            collate_fn = data_collator,
        )

        tf_validation_set = model.prepare_tf_dataset(
            Dataset.from_dict(tokenized_train_dataset[index_lists[cv_phase]]),
            shuffle = False,
            batch_size = batch_size,
            collate_fn = data_collator,
        )

        model.compile(optimizer = optimizer, metrics = ["accuracy"])

        #metric_callback = KerasMetricCallback(metric_fn = compute_metrics, eval_dataset = tf_validation_set)
        model.fit(x = tf_train_set, validation_data = tf_validation_set, epochs = 15)

        accuracy_metrics = tf.keras.metrics.Accuracy()
        for instance, label in tf_validation_set.as_numpy_iterator():
            prediction = model.predict(instance).logits
            prediction = tf.argmax(prediction, axis = 1)
            accuracy_metrics.update_state(label, prediction)

        cv_accuracy.append(accuracy_metrics.result().numpy())

    return cv_accuracy

In [20]:
data_collator = DataCollatorForMultipleChoice(tokenizer = tokenizer)

In [21]:
batch_size = 8

tf_full_train_set = model.prepare_tf_dataset(
    tokenized_train_dataset,
    shuffle = True,
    batch_size = batch_size,
    collate_fn = data_collator,
)

model.fit(x = tf_full_train_set, epochs = 10)

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


Epoch 1/10
25/25 [==============================] - 64s 671ms/step - loss: 1.6189
Epoch 2/10
25/25 [==============================] - 14s 553ms/step - loss: 1.6161
Epoch 3/10
25/25 [==============================] - 12s 498ms/step - loss: 1.6035
Epoch 4/10
25/25 [==============================] - 12s 481ms/step - loss: 1.6065
Epoch 5/10
25/25 [==============================] - 12s 463ms/step - loss: 1.6004
Epoch 6/10
25/25 [==============================] - 12s 461ms/step - loss: 1.5987
Epoch 7/10
25/25 [==============================] - 12s 479ms/step - loss: 1.6103
Epoch 8/10
25/25 [==============================] - 12s 462ms/step - loss: 1.6056
Epoch 9/10
25/25 [==============================] - 12s 466ms/step - loss: 1.6002
Epoch 10/10
25/25 [==============================] - 11s 457ms/step - loss: 1.6000


In [22]:
#avg_accuracy = cross_validation_training(cv = 5)

In [23]:
#np.mean(avg_accuracy)

# Inference for test set

In [24]:
debug = False

In [25]:
TEST_DATASET_DIRECTORY = os.path.join(DATASET_PATH, "test.csv")
test_df = pd.read_csv(TEST_DATASET_DIRECTORY)

In [26]:
from datasets import Dataset

test_dataset = Dataset.from_pandas(test_df)
test_dataset

Dataset({
    features: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E'],
    num_rows: 200
})

In [27]:
tokenized_test_dataset = test_dataset.map(multiple_choice_question_preprocessing_function)

  0%|          | 0/200 [00:00<?, ?ex/s]

In [28]:
tokenized_test_dataset

Dataset({
    features: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'input_ids', 'attention_mask'],
    num_rows: 200
})

In [29]:
from dataclasses import dataclass
from transformers.tokenization_utils_base import PreTrainedTokenizerBase, PaddingStrategy
from typing import Optional, Union
import tensorflow as tf


@dataclass
class DataCollatorForMultipleChoiceInference:
    """
    Data collator that will dynamically pad the inputs for multiple choice received.
    """

    tokenizer: PreTrainedTokenizerBase
    padding: Union[bool, str, PaddingStrategy] = True
    max_length: Optional[int] = None
    pad_to_multiple_of: Optional[int] = None

    def __call__(self, features):
        batch_size = len(features)
        num_choices = len(features[0]["input_ids"])
        flattened_features = [
            [{k: v[i] for k, v in feature.items()} for i in range(num_choices)] for feature in features
        ]
        flattened_features = sum(flattened_features, [])

        batch = self.tokenizer.pad(
            flattened_features,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors="tf",
        )

        batch = {k: tf.reshape(v, (batch_size, num_choices, -1)) for k, v in batch.items()}
        return batch

In [30]:
batch_size = 8

infer_data_collator = DataCollatorForMultipleChoiceInference(tokenizer = tokenizer)
tf_test_set = model.prepare_tf_dataset(
    tokenized_test_dataset,
    shuffle = False,
    batch_size = batch_size,
    collate_fn = infer_data_collator,
)

In [31]:
for instance in tf_test_set.take(1):
    print(instance)

{'input_ids': <tf.Tensor: shape=(8, 5, 139), dtype=int64, numpy=
array([[[    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1]],

       [[    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1]],

       [[    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1],
        [    0, 32251,     9, ...,     1,     1,     1]],

       ...,

       [[    0, 32251,     9, ...,     1,     1,     1],
    

In [32]:
test_logit_prediction = model.predict(tf_test_set).logits
test_logit_prediction

25/25 [==============================] - 7s 155ms/step


array([[ 9.64417681e-03,  3.01060677e-02,  1.52504072e-02,
         3.10377702e-02,  1.85330324e-02],
       [ 3.98059711e-02,  4.15419787e-02,  3.90307456e-02,
         4.03444432e-02,  3.27205881e-02],
       [ 1.35594956e-03, -6.73233019e-03, -2.92025798e-04,
        -1.08491592e-02, -7.22613791e-03],
       [ 2.92226896e-02,  1.88117363e-02,  2.55333260e-02,
         1.71978101e-02,  1.27098970e-02],
       [ 2.17927322e-02,  2.04328597e-02,  1.73902959e-02,
         2.06604563e-02,  2.24205032e-02],
       [ 3.89565751e-02,  4.53246981e-02,  4.35681567e-02,
         3.33121493e-02,  3.62779871e-02],
       [ 6.30862340e-02,  3.58253829e-02,  4.61064354e-02,
         3.87490839e-02,  2.94684060e-02],
       [ 1.20823532e-02,  1.15108155e-02,  5.60897542e-03,
         1.86363347e-02,  1.06057599e-02],
       [-1.56440884e-02, -1.77603252e-02, -2.08323747e-02,
        -2.13875305e-02, -2.03318149e-02],
       [ 3.47917303e-02,  1.43398694e-03,  9.73931327e-03,
         1.33657791e-02

In [33]:
test_top_k_values, test_top_k_indices = tf.math.top_k(test_logit_prediction, k = 3, sorted = True)
test_top_k_indices

<tf.Tensor: shape=(200, 3), dtype=int32, numpy=
array([[3, 1, 4],
       [1, 3, 0],
       [0, 2, 1],
       [0, 2, 1],
       [4, 0, 3],
       [1, 2, 0],
       [0, 2, 3],
       [3, 0, 1],
       [0, 1, 4],
       [0, 3, 2],
       [3, 0, 4],
       [0, 3, 4],
       [2, 1, 0],
       [3, 4, 0],
       [0, 1, 2],
       [2, 1, 4],
       [1, 4, 2],
       [0, 4, 3],
       [0, 3, 2],
       [1, 2, 4],
       [3, 1, 2],
       [4, 1, 3],
       [2, 0, 4],
       [2, 1, 4],
       [3, 1, 4],
       [4, 1, 3],
       [0, 4, 2],
       [1, 3, 4],
       [4, 1, 0],
       [2, 1, 4],
       [0, 3, 4],
       [2, 4, 1],
       [4, 3, 1],
       [0, 2, 3],
       [1, 4, 3],
       [3, 4, 0],
       [4, 0, 3],
       [0, 4, 3],
       [4, 0, 3],
       [4, 0, 2],
       [4, 0, 3],
       [3, 0, 1],
       [3, 1, 0],
       [3, 2, 1],
       [4, 3, 0],
       [0, 1, 3],
       [1, 4, 2],
       [2, 3, 4],
       [1, 4, 2],
       [1, 2, 3],
       [1, 3, 4],
       [4, 2, 1],
       [2, 1, 4]

In [34]:
def convert_label_to_letter(top_k_array):
    letter_array = []
    def label_to_letter(label):
        return chr(label + ord('A'))
    for num_option in top_k_array:
        letter_array.append(label_to_letter(num_option))
    return tf.constant(letter_array)

In [35]:
test_top_k_predictions = tf.map_fn(fn = lambda t: convert_label_to_letter(t), elems = test_top_k_indices, dtype = tf.string)
test_top_k_predictions

<tf.Tensor: shape=(200, 3), dtype=string, numpy=
array([[b'D', b'B', b'E'],
       [b'B', b'D', b'A'],
       [b'A', b'C', b'B'],
       [b'A', b'C', b'B'],
       [b'E', b'A', b'D'],
       [b'B', b'C', b'A'],
       [b'A', b'C', b'D'],
       [b'D', b'A', b'B'],
       [b'A', b'B', b'E'],
       [b'A', b'D', b'C'],
       [b'D', b'A', b'E'],
       [b'A', b'D', b'E'],
       [b'C', b'B', b'A'],
       [b'D', b'E', b'A'],
       [b'A', b'B', b'C'],
       [b'C', b'B', b'E'],
       [b'B', b'E', b'C'],
       [b'A', b'E', b'D'],
       [b'A', b'D', b'C'],
       [b'B', b'C', b'E'],
       [b'D', b'B', b'C'],
       [b'E', b'B', b'D'],
       [b'C', b'A', b'E'],
       [b'C', b'B', b'E'],
       [b'D', b'B', b'E'],
       [b'E', b'B', b'D'],
       [b'A', b'E', b'C'],
       [b'B', b'D', b'E'],
       [b'E', b'B', b'A'],
       [b'C', b'B', b'E'],
       [b'A', b'D', b'E'],
       [b'C', b'E', b'B'],
       [b'E', b'D', b'B'],
       [b'A', b'C', b'D'],
       [b'B', b'E', b'D'],
      

In [36]:
import csv
CSV_TEST_RESULT_DIRECTORY = os.path.join("/kaggle/working", "submission.csv")

In [37]:
# open the file in the write mode
with open(CSV_TEST_RESULT_DIRECTORY, 'w', newline = '') as f:
    # create the csv writer
    writer = csv.writer(f)
    header = ["id", "prediction"]
    writer.writerow(header)

    for index, top_k_prediction in enumerate(list(test_top_k_predictions)):
        row = [ index ]
        prediction_string = []
        for prediction in top_k_prediction:
            prediction_string.append(prediction.numpy().decode('utf-8'))
        row.append(" ".join(prediction_string))
        writer.writerow(row)